In [28]:
print("Hello world, welcome to the world of NUmPy!!")

Hello world, welcome to the world of NUmPy!!


In [10]:
# importing numpy library sa np

In [6]:
import numpy as np
a = np.array([[1,2,3],[2,3,4]])

In [8]:
a.ndim

2

In [9]:
 b= np.array([1,2,3,4,5])
b.ndim

1

In [16]:
# accessing an elememt from a
# a[m,n]
# where m is the row number and n is the col number.

In [14]:
a[0,1]

2

In [17]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,6],[4,6,9],[-3,-5,-9]]])

In [18]:
c.ndim

3

In [19]:
c[1,0,1]

3

In [ ]:
# shape function returns a tuple of the size of the array.

In [27]:
shape = c.shape
print(shape)

(2, 3, 3)


In [32]:
c.shape[1]

3

In [ ]:
# type() functon gives ty

In [33]:
type(c)

numpy.ndarray

In [ ]:
#sometimes you may get error here sa numpy is not imported after you came back to the notebook but there is nothing to worry about that. 
#it is not necessary to import it everytime . once imported , done fot the whole bunch of code.

In [5]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,3,5],[3,7,9]]])

In [6]:
arr.ndim

3

In [10]:
# if you are declaring a multidimensional array then the number of elements in the lists shuold be same otherwise you may get undesired result.
a= np.array([[1,2,3],[1,2,3,2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#here i am adding 5 in the 0th row to equal the no. of elements in both rows.

In [11]:
a= np.array([[1,2,3,5],[1,2,3,2]])

In [12]:
print(a)

[[1 2 3 5]
 [1 2 3 2]]


In [15]:
# now lets try making a 3 dimensional array.
a = np.array([[[1,2,5],[1,3,9]],[[-1,-2,-5],[-1,-3,-9]]])
a.ndim

3

In [2]:
"""
lets discuss about the shape property.
Shape returns a tuple.
"""

'\nlets discuss about the shape property.\nShape returns a tuple.\n'

In [5]:
import numpy as np
a = np.array([[[1,2,5],[1,3,9]],[[-1,-2,-5],[-1,-3,-9]]])
a.shape


(2, 2, 3)

In [7]:
""" in the above result a.shape returns a tuple (2,2,3) which means a contains 2 2-dim array, each 2-dim array contrains 2 1-dim array
and each 1-dim array contains 3 elements.
"""

' in the above result a.shape returns a tuple (2,2,3) which means a contains 2 2-dim array, each 2-dim array contrains 2 1-dim array\nand each 1-dim array contains 3 elements.\n'

In [8]:
a.shape[0]

2

In [9]:
a.shape[1]

2

In [10]:
a.shape[2]

3

In [ ]:
# size gives the total number of elements present in the array.

In [12]:
a.size 

12

In [13]:
# similarly there is another property in numpy that gives the total size of the array in terms of bytes.

In [14]:
a.nbytes

48

In [31]:
"""
here we are creating an array using np.ones method that creates an array of the input size. All the elements of the array will be 1.
The ones method is quite useful in initializing arrays for various numerical operations and is a fundamental function in the NumPy library.
 the following code creates an array containing 4 rows and 10 columns.
 """

'\nhere we are creating an array using np.ones method that creates an array of the input size. All the elements of the array will be 1.\nThe ones method is quite useful in initializing arrays for various numerical operations and is a fundamental function in the NumPy library.\n the following code creates an array containing 4 rows and 10 columns.\n '

In [27]:
b= np.ones((4,10),dtype=int)
print(b)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# arange function creates an array upto the number given in its argument.

In [18]:
C = np.arange(50)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [19]:
# we can also manpulate this array formation as per our need by changing the args value.
C = np.arange(20,100,5)
print(C)

[20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [20]:
#in the above rersult we tried to create an array that starts from 20 , ends at 100 and proceeds by taking jump of 5.

In [ ]:
"""
now lets learn how to shuffle data in an array using numoy methods.
To to so, we can use np.random.permutation function. its implementation is shown below.
"""

In [4]:
import numpy as np
a = np.arange(100)
A = np.random.permutation(a)
print(A)

[93 76  5 84 59 85 60 37 10 48 15 78 20 50 83 70 98 17 64 72 94 46 99 65
 82 16 43 41 36 47  6  3 18 45 30 54  8 77 90 63 25 21 19  0  2 75  7 42
 62 74 44 69 22 11 79 68 67 51 91 80 97 35 55 52 39 58 34 33 40  4 89 56
 61 53 95 26 23 32 71 28 31 57 88  9 81 49 29 13 86 92 12 87 24  1 73 14
 38 96 27 66]


In [6]:
""" under random method we have a lot of ither functions too. Suppose you want to get a random number number between 1 and 100. 
to do that we can use np.randoom.randint() method."""

In [10]:
random_int = np.random.randint(1,100)
print(random_int)
print(type(random_int))

25
<class 'int'>


In [ ]:
""" if we want to create a random matrtix of any order then we can use random.rand method.
it returns a random matrix of the order that you passed as an args in it. """

In [23]:
C = np.random.rand(2,3)
print(C)

[[0.26779071 0.10649595 0.73068877]
 [0.14109981 0.59126058 0.69462395]]


In [16]:
# Another important function in numpy library is reshape function which can be used to produce any shape of array from an existing array. 

In [13]:
a = np.arange(20)

In [ ]:
# here i am using reshape method to get a new array having 4 rows and 5 columns out of array 'a'.

In [14]:
b= np.reshape(a,(4,5))

In [15]:
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
x = np.arange(30)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [ ]:
# creating 3 dimensional array from x.

In [33]:
y = np.reshape(x,(2,3,5))
print(y)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [34]:
y.ndim

3

In [2]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
import numpy as np
b=np.array([[1,2,3,4,5], [6,7,8,9,0]])

In [4]:
# getting an element, here getting element of first row and fourth column
b[0,3]

4

In [6]:
# getting s[ecific row or col
b[0, :]

array([1, 2, 3, 4, 5])

In [7]:
b[ :, 2]

array([3, 8])

In [10]:
# a little fancy way to manipulate the elements can be:
# b[row, start:end:stepsize]

b[0, 1:4:2]
# note that end idx is exclusive. here 4th idx points to element 5 so its exclusive.

array([2, 4])

In [11]:
# changing a particular element or a complete row or col
b[0,2] = 10 
print(b)

[[ 1  2 10  4  5]
 [ 6  7  8  9  0]]


In [13]:
b[ :,1]=[10,12]
print(b)
# here 2nd item of every row is changed.

[[ 1 10 10  4  5]
 [ 6 12  8  9  0]]


In [14]:
# 3dim array
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

In [15]:
''' This creates a 3D array of shape (2, 2, 3):

2 blocks (or depth slices)

Each block has 2 rows 
Each row has 3 columns '''

' This creates a 3D array of shape (2, 2, 3):\n\n2 blocks (or depth slices)\n\nEach block has 2 rows\n\nEach row has 3 columns '

In [16]:
arr[0, 0, 0]  # Output: 1  => First block, first row, first column
arr[0, 1, 2]  # Output: 6  => First block, second row, third column
arr[1, 0, 1] # Output: 8 => second block, first row, second column

8

In [22]:
''' Problem statement: Create the given matrix using only numpy.
[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
'''

' Problem statement: Create the given matrix using only numpy.\n[1 1 1 1 1]\n [1 0 0 0 1]\n [1 0 9 0 1]\n [1 0 0 0 1]\n [1 1 1 1 1]\n'

In [21]:
# practice question
output = np.ones((5,5), dtype='int32')
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [1]:
####  Boolean masking and adavnced Indexing

In [11]:
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([  1,   2,   3,   4,   5,   6,   7,   7,   8,   9,  12,  13,  15,
        36,  37,  39,  20,  40,  42,  44,  45,  50,  52,  61,  72,  65,
        77,  88,  81,  90,  95,  19, 100, 123,  34,  51, 199, 145, 300])

In [12]:
arr = filedata.reshape(3,13)
print(arr)

[[  1   2   3   4   5   6   7   7   8   9  12  13  15]
 [ 36  37  39  20  40  42  44  45  50  52  61  72  65]
 [ 77  88  81  90  95  19 100 123  34  51 199 145 300]]


In [9]:
(filedata > 40) &(filedata<50)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [13]:
# to find if any value in a col is greater than 40
np.any(arr>50, axis=0)

array([ True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True])

In [ ]:
## this is it brother... I hope it helps you in your learing journey..Bye